version: '3.1'

services:

  dbpostgres:
    container_name: postgres
    image: postgres:16.1
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: dbt_db
    restart: always
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    security_opt:
      - no-new-privileges:true

  dbt:
    build:
      dockerfile: ./image/Dockerfile
    volumes:
     - ./dbt:/usr/app
    ports:
      - 8080:8080
    environment:
      - DBT_HOST=${DBT_HOST}
      - DBT_USER=${DBT_USER}
      - DBT_PASSWORD=${DBT_PASSWORD}